import java.util.Arrays;
import java.util.Scanner;
public class Main {
    static String password[]=new String[3];//password
    //static String name[]=new String[3];
    public static void main(String[] args){
        int index=0;
        Scanner sc=new Scanner(System.in);
        int yourResponse;
        PassengerDetails obj=new PassengerDetails();
        do{
            System.out.println("enter 1 for sign in ");
            System.out.println("enter 2 for sign up ");
            System.out.println("enter 3 for exit");
            yourResponse=sc.nextInt();
            switch (yourResponse){
                case 1:
                    System.out.println("enter your registerd id ");
                    int tempIndex=sc.nextInt();
                    System.out.println("enter your password ");
                    String tempPassword=sc.next();
                    if(password[tempIndex].equalsIgnoreCase(tempPassword))//to check two strings
                        System.out.println("\n successfully logged in");
                    else
                        System.out.println("wrong password or login id try again ");
                    break;
                case 2:
                    Details d[]=new Details[3];//creating an array for class Details
                    d[index]=new Details();
                    System.out.print("enter your name ");
                    String name1=sc.next();//scanning name
                    d[index].name=name1;
                    System.out.println("enter your age ");
                    int age=sc.nextInt();//scanning age
                    d[index].age=age;
                    System.out.println("enter new password ");
                    String password1=sc.next();//scanning passwords& storing it
                    password[index]=password1;
                    System.out.println("your autogenerated id is "+index+"\n");
                    index++;
                    break;
                case 3:
                    yourResponse=3;
                    System.out.println("thank you for using ");
                    break;
                /*case 23:
                    String names[]=obj.getName();
                    for(int k=0;k<names.length-1;k++) {//sorting String array
                        for(int j=k+1;j<names.length;j++){
                            if(names[k].compareToIgnoreCase(names[j])>0){
                                String temp=names[k];//swapping
                                names[k]=names[j];
                                names[j]=temp;
                            }
                        }
                    }
                    //System.out.println(Arrays.toString(names));
                    for(int i=0;i<3;i++)
                        System.out.println(names[i]);
                    break;*/
                default:
                    System.out.println("invalid response ");
            }
        }
        while(yourResponse!=3);
    }
}