package OldMaterial;
public class StringDifference {
//    You are given two strings s and t.
//    String t is generated by random shuffling string s and then add one more letter at a random position.
//    Return the letter that was added to t.
//    Example 1:
//
//    Input: s = "abcd", t = "abcde"
//    Output: "e"
//    Explanation: 'e' is the letter that was added.
    public static void main(String[] args) {
        String a="";
        String t="y";
        char[] aArr=a.toCharArray();
        char[] tArr=t.toCharArray();
        int i,j;
        boolean notPresent=true;
        for(i=0;i<t.length();i++){
            for(j=0;j<a.length();j++){
                if(tArr[i]==aArr[j] && aArr[j]!=1){
                    aArr[j]='1';
                    notPresent=false;
                    break;
                }
            }
//            System.out.println(notPresent);
            if(notPresent)
                System.out.println(tArr[i]);
            notPresent=true;
        }
    }
}
